apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-simple
spec:
  containers:
  - name: gpu-test
    image: nvidia/cuda:13.0.0-base-ubuntu22.04
    command: ["/bin/bash", "-c"]
    args: ["echo 'NVIDIA_VISIBLE_DEVICES: '$NVIDIA_VISIBLE_DEVICES && ls -la /dev/nvidia* && echo 'GPU devices found' || echo 'No GPU devices'"]
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: "compute,utility"
    resources:
      limits:
        nvidia.com/gpu: "1"
  restartPolicy: Never
