{
 "title": "Vicugna Kubernetes Dashboard",
 "description": "My Vicugna Kubernetes Dashboard",
 "tags": [ "prometheus" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Memory Per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  container_memory_working_set_bytes{namespace!=\"\",container!=\"POD\",container!=\"\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)\n) / sum(node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  rate(container_cpu_usage_seconds_total{namespace!=\"\",container!=\"POD\",container!=\"\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) \n  / \n  sum(rate(node_cpu_seconds_total[5m]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Power Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{node=\"zeratul\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{node=\"zeratul\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}